"""Audit the schwa tables against Wiktionary and pack the corrections.

Indonesian headwords on en.wiktionary.org mark the pepet vowel: "ê" is /ə/,
"é" and "è" are not. Where a fully marked headword reads a word with fewer
schwas than the lexicon and dictionary do, Wiktionary wins, and where neither
lists the word at all, Wiktionary places it. Both go into
src/data/schwa-wiktionary.ts. A word with more than one etymology is a
homograph, whether or not every sense is marked, and is left to
data/homographs-verified.tsv: Wiktionary marks only the noun sense of "seri",
/séri/, and says nothing about /səri/, radiance.

Of a word the tables already list, only a reading that removes a schwa is
taken. The two sources fail in
opposite directions: the dictionary over-reads the pepet in words KBBI marks
"é" (bébék, mérah, cétak), and Wiktionary over-marks "ê" in words KBBI marks
"é" (cêcêr for /cécér/, sênjang for /sénjang/). A reading that adds a schwa
is printed for review instead. A word the homograph table already splits by
part of speech is left to that rule.

A reading counts only when the marked headword and the IPA line agree. Each
alone is unreliable. The IPA is typed by hand and contradicts the headword
often: "bènsin" carries /bənˈsin/, and "pênganggaran" carries /peŋ.aŋˈɡar.an/.
The headword is sometimes marked with "ê" where /ɛ/ is meant: "bawêl" and
"rêwêl" sit next to /ˈbawɛl/ and /ˈrɛwɛl/, and KBBI has /bawél/ and /réwél/.

Dev-only: run once per Wiktionary refresh. The input is the kaikki.org
extract of the Indonesian Wiktionary; it is not vendored.

    python3 scripts/dump-wiktionary.py <kaikki.org-dictionary-Indonesian.jsonl>

The audit is printed to stdout as `word  old  new  taken|added|review`, one
word per line, so a refresh can be reviewed before it is committed.

Source: https://kaikki.org/dictionary/Indonesian/ (CC BY-SA 4.0).
"""

# SPDX-License-Identifier: MIT
# Copyright (c) 2026 snowfluke

import importlib.util
import json
import re
import sys
from pathlib import Path

HEADER = (
    "// Generated by scripts/dump-wiktionary.py. Do not edit.\n"
    "// SPDX-License-Identifier: MIT\n"
    "// Copyright (c) 2026 snowfluke\n"
)
ROOT = Path(__file__).resolve().parent.parent

# The phonemic reading, between slashes. The phonetic one in brackets repeats
# it with stress and syllable dots, which add nothing here.
PHONEMIC = re.compile(r"^/(.+)/$")
E_LIKE = {"e", "ɛ", "ə"}


def load_read_head():
    """Borrow `read_head` from the homograph audit, so both read a headword the same way."""
    path = Path(__file__).with_name("verify-homographs.py")
    spec = importlib.util.spec_from_file_location("verify_homographs", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.read_head


def packed_lines(name: str) -> list[str]:
    """The lines of one packed table in src/data."""
    source = (ROOT / "src" / "data" / name).read_text(encoding="utf-8")
    return source.split("= ", 1)[1].strip().rstrip(";").strip("'").split("\\n")


def packed_masks(name: str) -> dict[str, int]:
    """Read one of the `word hexMask` tables in src/data."""
    masks: dict[str, int] = {}
    for line in packed_lines(name):
        space = line.rfind(" ")
        masks[line[:space]] = int(line[space + 1 :], 16)
    return masks


def homograph_words() -> set[str]:
    """Words the part-of-speech rules already split, packed as `word classes m1 m2`."""
    return {line.split(" ")[0] for line in packed_lines("homographs.ts")}


def ipa_mask(word: str, ipa: str) -> int | None:
    """The schwa bitmask a phonemic IPA line gives, or None if it cannot be aligned."""
    match = PHONEMIC.match(ipa.strip())
    if not match:
        return None
    slots = [c for c in match.group(1) if c in E_LIKE]
    # A line whose e-like vowels do not line up one-to-one with the spelling's
    # `e`s cannot say which `e` is which.
    if len(slots) != word.count("e"):
        return None
    mask = 0
    for index, slot in enumerate(slots):
        if slot == "ə":
            mask |= 1 << index
    return mask


def entry_mask(word: str, entry: dict, read_head) -> int | None:
    """The reading one entry gives, when its marked headword and its IPA agree."""
    heads = set()
    for template in entry.get("head_templates", []):
        head = template.get("args", {}).get("head")
        got = read_head(word, head) if head else None
        # A head with any bare `e` left is unmarked there, and proves nothing.
        if got is not None and got[1] == 0:
            heads.add(got[0])
    ipas = {ipa_mask(word, sound.get("ipa", "")) for sound in entry.get("sounds", [])}
    ipas.discard(None)
    agreed = heads & ipas
    return next(iter(agreed)) if len(agreed) == 1 and len(heads) == 1 and len(ipas) == 1 else None


def wiktionary_masks(dump: Path) -> dict[str, int]:
    """One reading per word. A word with two readings, or two etymologies, is dropped."""
    read_head = load_read_head()
    readings: dict[str, set[int]] = {}
    etymologies: dict[str, set[str | None]] = {}
    with dump.open(encoding="utf-8") as handle:
        for row in handle:
            entry = json.loads(row)
            word = entry.get("word", "")
            if entry.get("lang_code") != "id" or "e" not in word or not re.fullmatch(r"[a-z]+", word):
                continue
            etymologies.setdefault(word, set()).add(entry.get("etymology_number"))
            mask = entry_mask(word, entry, read_head)
            if mask is not None:
                readings.setdefault(word, set()).add(mask)
    return {
        word: next(iter(masks))
        for word, masks in readings.items()
        if len(masks) == 1 and len(etymologies[word]) == 1
    }


def main() -> None:
    current = (
        packed_masks("lexicon.ts") | packed_masks("schwa-dict.ts") | packed_masks("schwa-overrides.ts")
    )
    wiktionary = wiktionary_masks(Path(sys.argv[1]))
    split_by_pos = homograph_words()

    corrections: list[str] = []
    added = 0
    for word, mask in sorted(wiktionary.items()):
        old = current.get(word)
        if old == mask or word in split_by_pos:
            continue
        if old is None:
            corrections.append(f"{word} {mask:x}")
            added += 1
            print(f"{word}\t-\t{mask:x}\tadded")
            continue
        taken = mask & ~old == 0
        if taken:
            corrections.append(f"{word} {mask:x}")
        print(f"{word}\t{old:x}\t{mask:x}\t{'taken' if taken else 'review'}")

    out = ROOT / "src" / "data" / "schwa-wiktionary.ts"
    out.write_text(
        f"{HEADER}\n"
        f"/**\n"
        f" * Words whose marked Wiktionary headword contradicts the lexicon or the dictionary,\n"
        f" * and words neither lists.\n"
        f" * Packed as `word hexMask` per line, where bit i marks the i-th `e` as a schwa.\n"
        f" */\n"
        f"export const SCHWA_WIKTIONARY: string = {chr(10).join(corrections)!r};\n"
    )
    checked = sum(1 for word in wiktionary if word in current)
    print(f"checked {checked} words, corrected {len(corrections) - added}, added {added}", file=sys.stderr)
    print(f"wrote {out}", file=sys.stderr)


if __name__ == "__main__":
    main()
