"""Pack English pronunciations for words Indonesian has no answer for.

Indonesian text carries English words, and reading them with Indonesian
grapheme rules makes `event` into `efent`. This maps ipa-dict's English IPA
onto the phoneme set this library already emits, which is the approximation an
Indonesian speaker makes anyway.

Three filters keep it from touching anything Indonesian:

1. Words any Indonesian list already answers are dropped, so English is only
   ever consulted last.
2. Only reasonably common English words are kept, since the long tail of a
   125,000-word dictionary is mostly names.
3. data/indonesian-proper-nouns.tsv blocks the names that survive both, such
   as `jakarta` and `april`, which English dictionaries also carry.

    uv run scripts/dump-english.py <ipa-dict en_US.txt> <common-words.txt>

Source: https://github.com/open-dict-data/ipa-dict (MIT).
"""

# SPDX-License-Identifier: MIT
# Copyright (c) 2026 snowfluke

import re
import sys
from pathlib import Path

HEADER = (
    "// Generated by scripts/dump-english.py. Do not edit.\n"
    "// SPDX-License-Identifier: MIT\n"
    "// Copyright (c) 2026 snowfluke\n"
)
ROOT = Path(__file__).resolve().parent.parent
MIN_LENGTH = 3

# English sounds rewritten as the nearest thing this library emits. Applied in
# order, so the longer sequences win. `dʒ` is parked first because the plain
# `ʒ` rule below would otherwise eat its second half.
SOUND_MAP: list[tuple[str, str]] = [
    ("dʒ", "\x01"),
    ("aʊ", "aʊ"), ("aɪ", "aɪ"), ("ɔɪ", "ɔɪ"),
    ("oʊ", "o"), ("eɪ", "e"),
    ("ɝ", "ər"), ("ɚ", "ər"),
    ("ɪ", "i"), ("ɛ", "e"), ("ɑ", "a"), ("ʊ", "u"),
    ("æ", "a"), ("ɔ", "o"), ("ʌ", "a"),
    ("ɫ", "l"), ("ɹ", "r"), ("ɡ", "g"),
    ("ʒ", "ʃ"), ("θ", "t"), ("ð", "d"), ("v", "f"),
    ("\x01", "dʒ"),
]
DROPPED = "ˈˌː()"


def to_local(ipa: str) -> str:
    """Rewrite one English pronunciation in this library's phoneme set."""
    text = "".join(c for c in ipa.strip().strip("/") if c not in DROPPED)
    for source, target in SOUND_MAP:
        text = text.replace(source, target)
    return text


def blocked_words() -> set[str]:
    words: set[str] = set()
    path = ROOT / "data" / "indonesian-proper-nouns.tsv"
    for row in path.read_text(encoding="utf-8").splitlines():
        if not row.strip() or row.startswith("#"):
            continue
        words.update(row.split("\t")[1].split())
    return words


def indonesian_words() -> set[str]:
    """Everything the Indonesian sources already answer."""
    words: set[str] = set()
    for name in ("schwa-dict.ts", "lexicon.ts", "schwa-overrides.ts"):
        source = (ROOT / "src" / "data" / name).read_text(encoding="utf-8")
        packed = source.split("= ", 1)[1].strip().rstrip(";").strip("'")
        for line in packed.split("\\n"):
            words.add(line[: line.rfind(" ")])
    return words


def main() -> None:
    common = {
        w.strip()
        for w in Path(sys.argv[2]).read_text(encoding="utf-8").splitlines()
        if w.strip()
    }
    skip = indonesian_words() | blocked_words()

    entries: dict[str, str] = {}
    for row in Path(sys.argv[1]).read_text(encoding="utf-8").splitlines():
        parts = row.split("\t")
        if len(parts) < 2:
            continue
        word = parts[0]
        if len(word) < MIN_LENGTH or not re.fullmatch(r"[a-z]+", word):
            continue
        if word not in common or word in skip:
            continue

        spoken = to_local(parts[1].split(",")[0])
        # A mapping that left anything unrecognised would inject a symbol the
        # rest of the library never emits, so it is dropped instead.
        if not spoken or re.search(r"[^a-zəŋɲʃʒʔɪʊ]", spoken):
            continue
        entries[word] = spoken

    lines = "\n".join(f"{w} {p}" for w, p in sorted(entries.items()))
    out = ROOT / "src" / "data" / "english.ts"
    out.write_text(
        f"{HEADER}\n"
        f"/**\n"
        f" * English pronunciations for words no Indonesian list answers,\n"
        f" * from ipa-dict (MIT), mapped onto this library's phoneme set.\n"
        f" *\n"
        f" * Packed as `word phonemes` per line.\n"
        f" */\n"
        f"export const ENGLISH: string = {lines!r};\n"
    )
    print(f"{len(entries)} English entries -> {out}")


if __name__ == "__main__":
    main()
