"""Pack Bookbot's Indonesian lexicon into a fallback schwa table.

The curated dictionary in src/data/schwa-dict.ts answers first and is right on
native vocabulary, where this lexicon is not: it reads memang, desa, merah and
bebas without a schwa. This is only ever consulted for words that dictionary
does not list, where it beats the affix rules on both counts, correcting
mədia to media and pəmerintah to pəmərintah.

Only the schwa pattern is taken. The rest of the lexicon's IPA is discarded,
since the phoneme mapping here is the port's own.

    uv run scripts/dump-lexicon.py <path-to>/lexicon_id.tsv

Source: https://github.com/bookbot-kids/g2p_id (Apache-2.0).
"""

# SPDX-License-Identifier: MIT
# Copyright (c) 2026 snowfluke

import csv
import re
import sys
from pathlib import Path

HEADER = (
    "// Generated by scripts/dump-lexicon.py. Do not edit.\n"
    "// SPDX-License-Identifier: MIT\n"
    "// Copyright (c) 2026 snowfluke\n"
)
ROOT = Path(__file__).resolve().parent.parent


def schwa_masks(tsv_path: Path) -> dict[str, int]:
    """Read each entry's `e` and `ə` slots, in order, as a bitmask."""
    masks: dict[str, int] = {}
    for row in tsv_path.read_text(encoding="utf-8").splitlines():
        parts = row.split("\t")
        if len(parts) < 2:
            continue
        word, phonemes = parts[0], parts[1]
        if not re.fullmatch(r"[a-z]+", word):
            continue

        slots = [p for p in phonemes.split() if p in ("e", "ə")]
        # An entry whose vowel count disagrees with its spelling cannot be
        # aligned, so it is dropped rather than guessed at.
        if len(slots) != word.count("e"):
            continue

        mask = 0
        for index, slot in enumerate(slots):
            if slot == "ə":
                mask |= 1 << index
        masks[word] = mask
    return masks


def main() -> None:
    lexicon = schwa_masks(Path(sys.argv[1]))

    # Words the curated dictionary already answers are left out entirely, so
    # the fallback can never override it and the table stays smaller.
    curated = set()
    dict_source = (ROOT / "src" / "data" / "schwa-dict.ts").read_text(encoding="utf-8")
    packed = dict_source.split("= ", 1)[1].strip().rstrip(";").strip("'")
    for line in packed.split("\\n"):
        curated.add(line[: line.rfind(" ")])

    novel = {w: m for w, m in lexicon.items() if w not in curated}
    lines = "\n".join(f"{w} {m:x}" for w, m in sorted(novel.items()))

    out = ROOT / "src" / "data" / "lexicon.ts"
    out.write_text(
        f"{HEADER}\n"
        f"/**\n"
        f" * Schwa patterns from Bookbot's Indonesian lexicon (Apache-2.0),\n"
        f" * limited to words the curated dictionary does not list.\n"
        f" *\n"
        f" * Packed as `word hexMask` per line, where bit i marks the i-th `e`\n"
        f" * as a schwa.\n"
        f" */\n"
        f"export const LEXICON: string = {lines!r};\n"
    )
    print(f"{len(lexicon)} lexicon entries, {len(novel)} not already curated -> {out}")


if __name__ == "__main__":
    main()
