"""Dump Bookbot's Indonesian POS tagger and homograph table into packed
TypeScript data modules. Dev-only: run once per upstream data bump.

    uv run --with nltk scripts/dump-pos.py <path-to-bookbot-g2p_id-checkout>

Source: https://github.com/bookbot-kids/g2p_id (Apache-2.0).
"""

# SPDX-License-Identifier: MIT
# Copyright (c) 2026 snowfluke
import pickle
import sys
from pathlib import Path

HEADER = (
    "// Generated by scripts/dump-pos.py. Do not edit.\n"
    "// SPDX-License-Identifier: MIT\n"
    "// Copyright (c) 2026 snowfluke\n"
)

# Bookbot maps its coarse homograph POS letters onto the POSP tagset.
POS_GROUPS = {
    "N": ["B-NNO", "B-NNP", "B-PRN", "B-PRK"],
    "V": ["B-VBI", "B-VBT", "B-VBP", "B-VBL", "B-VBE"],
    "A": ["B-ADJ"],
    "P": ["B-PAR"],
}


def dump_tagger(pickle_path: Path, out: Path) -> int:
    weights, tagdict, classes = pickle.loads(pickle_path.read_bytes())
    tags = sorted(classes)
    index = {tag: i for i, tag in enumerate(tags)}

    lines = []
    for feature, scores in sorted(weights.items()):
        assert "\t" not in feature and "\n" not in feature, feature
        packed = ",".join(f"{index[t]}:{w:g}" for t, w in scores.items() if w != 0)
        if packed:
            lines.append(f"{feature}\t{packed}")

    known = "\n".join(f"{word}\t{index[tag]}" for word, tag in sorted(tagdict.items()))

    out.write_text(
        f"{HEADER}\n"
        f"/** POSP tags, sorted. Weights and the tag dictionary refer to these by index. */\n"
        f"export const TAGS: readonly string[] = {tags!r};\n\n"
        f'/** Packed perceptron weights: `feature\\ttagIndex:weight,...` per line. */\n'
        f"export const WEIGHTS: string = {chr(10).join(lines)!r};\n\n"
        f'/** Packed unambiguous words: `word\\ttagIndex` per line. Checked before the model. */\n'
        f"export const TAG_DICT: string = {known!r};\n\n"
        f"/** POSP tags that count as each coarse homograph class. */\n"
        f"export const POS_GROUPS: Readonly<Record<string, readonly string[]>> = {POS_GROUPS!r};\n"
    )
    return len(lines)


def dump_homographs(tsv_path: Path, out: Path) -> int:
    """Pack the curated homograph rules. See data/homographs-verified.tsv."""
    lines = []
    for row in tsv_path.read_text(encoding="utf-8").splitlines():
        if not row.strip() or row.startswith("#"):
            continue
        word, class_1, mask_1, class_2, mask_2, _evidence = row.split("\t")
        assert len(class_1) == 1 and len(class_2) == 1, row
        lines.append(f"{word} {class_1}{class_2} {int(mask_1, 16):x} {int(mask_2, 16):x}")

    out.write_text(
        f"{HEADER}\n"
        f'/** Packed homographs: `word class1class2 maskForClass1 maskForClass2`.\n'
        f' * A class of `-` matches no tag, so that side always falls through\n'
        f' * to the schwa dictionary. */\n'
        f"export const HOMOGRAPHS: string = {chr(10).join(lines)!r};\n"
    )
    return len(lines)


def dump_collocations(tsv_path: Path, out: Path) -> int:
    """Pack the collocation rules. See data/homographs-collocations.tsv."""
    lines = []
    for row in tsv_path.read_text(encoding="utf-8").splitlines():
        if not row.strip() or row.startswith("#"):
            continue
        word, mask, triggers, _evidence = row.split("\t")
        assert triggers.strip(), row
        lines.append(f"{word} {int(mask, 16):x} {' '.join(triggers.split())}")

    out.write_text(
        f"{HEADER}\n"
        f'/** Packed collocations: `word mask trigger...` per line. A trigger within\n'
        f' * COLLOCATION_WINDOW words selects the reading `mask` describes. */\n'
        f"export const COLLOCATIONS: string = {chr(10).join(lines)!r};\n\n"
        f"/** How many words either side of a homograph are searched for a trigger. */\n"
        f"export const COLLOCATION_WINDOW: number = 4;\n"
    )
    return len(lines)


def main() -> None:
    src = Path(sys.argv[1])
    if (src / "g2p_id" / "resources").is_dir():
        src = src / "g2p_id" / "resources"
    out = Path(__file__).resolve().parent.parent / "src" / "data"

    # The tagger weights rarely change; regenerate them only when the pickle
    # is at hand, so the homograph table can be refreshed on its own.
    pickle_path = src / "id_posp_tagger.pickle"
    if pickle_path.exists():
        print(f"wrote {dump_tagger(pickle_path, out / 'pos-model.ts')} tagger features")
    else:
        print(f"skipped tagger: {pickle_path} not found")

    verified = Path(__file__).resolve().parent.parent / "data" / "homographs-verified.tsv"
    print(f"wrote {dump_homographs(verified, out / 'homographs.ts')} homographs")

    collocations = Path(__file__).resolve().parent.parent / "data" / "homographs-collocations.tsv"
    print(f"wrote {dump_collocations(collocations, out / 'collocations.ts')} collocation rules")


if __name__ == "__main__":
    main()
