"""Pack English pronunciations for words Indonesian has no answer for.

Indonesian text carries English words and foreign names, and reading them with
Indonesian spelling rules gives `efent` for `event` and `dennj` for `denny`.
This maps ipa-dict's English IPA onto the phoneme set this library already
emits, which is the approximation an Indonesian speaker makes anyway.

Two filters keep it away from Indonesian:

1. Words any Indonesian source already places are dropped, so English is only
   ever consulted last.
2. data/indonesian-proper-nouns.tsv blocks the names and naturalised loanwords
   that survive the first filter, such as `jakarta` and `april`, which English
   dictionaries also carry.

    uv run scripts/dump-english.py <ipa-dict en_US.txt>

Source: https://github.com/open-dict-data/ipa-dict (MIT).
"""

# SPDX-License-Identifier: MIT
# Copyright (c) 2026 snowfluke

import re
import sys
from pathlib import Path

HEADER = (
    "// Generated by scripts/dump-english.py. Do not edit.\n"
    "// SPDX-License-Identifier: MIT\n"
    "// Copyright (c) 2026 snowfluke\n"
)
ROOT = Path(__file__).resolve().parent.parent
MIN_LENGTH = 3

# English sounds rewritten as the nearest thing this library emits, applied in
# order. Diphthongs and `dʒ` are parked as placeholders first, so the
# single-symbol rules below cannot eat half of one: without that, `maɪkəl`
# comes out as `maikəl`.
SOUND_MAP: list[tuple[str, str]] = [
    ("dʒ", "\x01"), ("aɪ", "\x02"), ("aʊ", "\x03"), ("ɔɪ", "\x04"),
    ("oʊ", "o"), ("eɪ", "e"), ("ɝ", "ər"), ("ɚ", "ər"),
    ("ɪ", "i"), ("ɛ", "e"), ("ɑ", "a"), ("ʊ", "u"),
    ("æ", "a"), ("ɔ", "o"), ("ʌ", "a"),
    ("ɫ", "l"), ("ɹ", "r"), ("ɡ", "g"),
    ("ʒ", "ʃ"), ("θ", "t"), ("ð", "d"), ("v", "f"),
    ("\x01", "dʒ"), ("\x02", "aɪ"), ("\x03", "aʊ"), ("\x04", "ɔɪ"),
]
DROPPED = "ˈˌː()"
EMITTED = re.compile(r"^[a-zəŋɲʃʒʔɪʊɔ]+$")


def to_local(ipa: str) -> str:
    """Rewrite one English pronunciation in this library's phoneme set."""
    text = "".join(c for c in ipa.strip().strip("/") if c not in DROPPED)
    for source, target in SOUND_MAP:
        text = text.replace(source, target)
    return text


def blocked_words() -> set[str]:
    words: set[str] = set()
    path = ROOT / "data" / "indonesian-proper-nouns.tsv"
    for row in path.read_text(encoding="utf-8").splitlines():
        if not row.strip() or row.startswith("#"):
            continue
        words.update(row.split("\t")[1].split())
    return words


def indonesian_words() -> set[str]:
    """Everything the Indonesian sources already place."""
    words: set[str] = set()
    for name in ("schwa-dict.ts", "lexicon.ts", "schwa-overrides.ts"):
        source = (ROOT / "src" / "data" / name).read_text(encoding="utf-8")
        packed = source.split("= ", 1)[1].strip().rstrip(";").strip("'")
        for line in packed.split("\\n"):
            words.add(line[: line.rfind(" ")])
    return words


def main() -> None:
    skip = indonesian_words() | blocked_words()

    entries: dict[str, str] = {}
    for row in Path(sys.argv[1]).read_text(encoding="utf-8").splitlines():
        parts = row.split("\t")
        if len(parts) < 2:
            continue
        word = parts[0]
        if len(word) < MIN_LENGTH or not re.fullmatch(r"[a-z]+", word):
            continue
        if word in skip:
            continue

        spoken = to_local(parts[1].split(",")[0])
        # A mapping that left anything unrecognised would inject a symbol the
        # rest of the library never emits, so it is dropped instead.
        if not spoken or not EMITTED.match(spoken):
            continue
        entries[word] = spoken

    lines = "\n".join(f"{w} {p}" for w, p in sorted(entries.items()))
    out = ROOT / "src" / "data" / "english.ts"
    out.write_text(
        f"{HEADER}\n"
        f"/**\n"
        f" * English pronunciations for words no Indonesian source places,\n"
        f" * from ipa-dict (MIT), mapped onto this library's phoneme set.\n"
        f" *\n"
        f" * Packed as `word phonemes` per line.\n"
        f" */\n"
        f"export const ENGLISH: string = {lines!r};\n"
    )
    print(f"{len(entries):,} English entries -> {out}")


if __name__ == "__main__":
    main()
