"""Dump the upstream g2p-id CRF syllabifier and schwa dictionary into packed
TypeScript data modules. Dev-only: run once per upstream data bump.

    uv run --with python-crfsuite scripts/dump-model.py <path-to-g2p-id-checkout>
"""

# SPDX-License-Identifier: MIT
# Copyright (c) 2026 snowfluke
import csv
import sys
from pathlib import Path

import pycrfsuite

HEADER = (
    "// Generated by scripts/dump-model.py. Do not edit.\n"
    "// SPDX-License-Identifier: MIT\n"
    "// Copyright (c) 2026 snowfluke\n"
)


def dump_model(model_path: Path, out: Path) -> None:
    tagger = pycrfsuite.Tagger()
    tagger.open(str(model_path))
    info = tagger.info()

    # Two labels only: O (continue) and S (syllable boundary).
    assert set(info.labels) == {"O", "S"}, info.labels

    weights: dict[str, list[float]] = {}
    for (attr, label), weight in info.state_features.items():
        assert "\t" not in attr and "\n" not in attr, attr
        weights.setdefault(attr, [0.0, 0.0])["OS".index(label)] = weight

    lines = []
    for attr, (w_o, w_s) in weights.items():
        # Most features are antisymmetric; store one weight instead of two.
        if w_o == -w_s and w_o != 0.0:
            lines.append(f"{attr}\t{w_o!r}")
        else:
            lines.append(f"{attr}\t{w_o!r}\t{w_s!r}")

    trans = [info.transitions[(a, b)] for a in "OS" for b in "OS"]
    body = "\n".join(lines)
    out.write_text(
        f"{HEADER}\n"
        f"/** Transition weights, row-major over `[from, to]` with labels `[O, S]`. */\n"
        f"export const TRANSITIONS: readonly number[] = [{', '.join(map(repr, trans))}];\n\n"
        f'/** Packed state features: `attr\\tw` (antisymmetric) or `attr\\twO\\twS`, newline separated. */\n'
        f"export const STATE_FEATURES: string = {body!r};\n"
    )


def dump_schwa(csv_path: Path, out: Path) -> None:
    entries = []
    with csv_path.open(encoding="utf-8") as handle:
        reader = csv.reader(handle)
        next(reader)
        for word, schwa_word in reader:
            assert schwa_word.replace("ê", "e") == word, (word, schwa_word)
            # Bit i is set when the i-th `e` of the word is a schwa.
            mask = 0
            for index, char in enumerate(c for c in schwa_word if c in "eê"):
                if char == "ê":
                    mask |= 1 << index
            entries.append(f"{word} {mask:x}")
    out.write_text(
        f"{HEADER}\n"
        f'/** Packed schwa dictionary: `word hexMask` per line, where bit i marks the i-th `e` as a schwa. */\n'
        f"export const SCHWA_DICT: string = {chr(10).join(entries)!r};\n"
    )


def dump_overrides(tsv_path: Path, out: Path) -> int:
    """Pack the corrections to the upstream dictionary. See data/schwa-overrides.tsv."""
    lines = []
    for row in tsv_path.read_text(encoding="utf-8").splitlines():
        if not row.strip() or row.startswith("#"):
            continue
        word, mask, _evidence = row.split("\t")
        lines.append(f"{word} {int(mask, 16):x}")

    out.write_text(
        f"{HEADER}\n"
        f'/** Packed corrections to the schwa dictionary: `word hexMask` per line. */\n'
        f"export const SCHWA_OVERRIDES: string = {chr(10).join(lines)!r};\n"
    )
    return len(lines)


def main() -> None:
    src = Path(sys.argv[1]) / "g2p_id"
    out = Path(__file__).resolve().parent.parent / "src" / "data"
    out.mkdir(parents=True, exist_ok=True)
    dump_model(src / "model" / "syllabifier.crfsuite", out / "syllabifier-model.ts")
    dump_schwa(src / "data" / "schwa_dict.csv", out / "schwa-dict.ts")
    overrides = Path(__file__).resolve().parent.parent / "data" / "schwa-overrides.tsv"
    print(f"wrote {dump_overrides(overrides, out / 'schwa-overrides.ts')} overrides")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
