// Generated by scripts/dump-pos.py. Do not edit.
// SPDX-License-Identifier: MIT
// Copyright (c) 2026 snowfluke

/** Packed homographs: `word class1class2 maskForClass1 maskForClass2`.
 * A class of `-` matches no tag, so that side always falls through
 * to the schwa dictionary. */
export const HOMOGRAPHS: string = 'apel -V 0 0\nketel -A 0 3\nletak AN 0 1\nleter A- 0 0\npening A- 1 0\npepet VN 0 3\nper NP 0 1\nrebak A- 0 0\nrembes A- 0 0\nseret V- 0 0\nterapi NA 0 1';
