// Generated by scripts/dump-model.py. Do not edit.
// SPDX-License-Identifier: MIT
// Copyright (c) 2026 snowfluke

/** Packed corrections to the schwa dictionary: `word hexMask` per line. */
export const SCHWA_OVERRIDES: string = 'mental 0\nterapi 0\nserong 0\nteknologi 0\nmetode 0\nmedan 0';
